import Nav from '../components/nav'
import Header from '../components/header'
import { GlobalContextProvider } from './Context/store'
import '../../globals.css'
import './layout.scss'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <GlobalContextProvider>
          <Header />
          <Nav />
          {children}
        </GlobalContextProvider>
      </body>
    </html>
  )
}

